development:
  adapter: postgresql
  encoding: unicode
  database: NodeZen_development
  pool: 5
test:
  adapter: postgresql
  encoding: unicode
  database: NodeZen_test
  pool: 5
production:
  adapter: postgresql
  encoding: unicode
  database: NodeZen_production
  pool: 5